### ISSUE TITLE
Allow override of browser shortcuts

### ISSUE THREAD

**Issue by lloydcotten** [philippbosch/ng-shortcut#1]
Would you be open to a PR for an option to allow the shortcut to override and prevent default behavior of built in browser shortcuts (such as `Ctrl+O`, `Ctrl+S`, `Ctrl+P`, etc)?

I'm thinking of adding an attribute called `preventDefault` and call `e.preventDefault();` if that is enabled on the directive.

**Comment by philippbosch** [comment]
I'd be open to that – but I'd suggest to name the attribute something like `shortcutPreventDefault`.

**Comment by lloydcotten** [comment]
OK - thanks for the quick response.  I will use that attribute name.

**Comment by philippbosch** [comment]
PR merged. Closing.
